version: "3.7"

services:
    nodebb:
        container_name: nodebb
        build: .
        restart: always
        ports:
            - 4567:4567
        volumes:
            - nodebb-files:/opt/nodebb/public/uploads
            - nodebb-config:/etc/nodebb
        depends_on:
            - mongodb
        networks:
            - net-nodebb

    mongodb:
        container_name: mongodb
        image: bitnami/mongodb:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: admin
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
            - nodebb-data:/bitnami/mongodb
        networks:
            - net-nodebb

networks:
    net-nodebb:
        driver: bridge

volumes:
    nodebb-files:
        name: nodebb-files
    nodebb-config:
        name: nodebb-config
    nodebb-data:
        name: nodebb-data
